language: java
jdk:
  - openjdk8

script:
  - sh build-jar.sh
  - sh test.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - mv rars.jar rars_`git rev-parse --short HEAD`.jar
  - bash upload.sh rars_`git rev-parse --short HEAD`.jar

branches:
  only:
    - master
